### ISSUE TITLE
CookCLI cannot be opened on a mac

### ISSUE THREAD

**Issue by lenniecottrell** [cooklang/CookCLI#14]
Very possible I just don't know what I'm doing, but trying to run the CLI on a mac runs me into the attached error. I'm using the full file path when I run it.

<img width="257" alt="Screen Shot 2021-10-29 at 3 00 01 PM" src="https://user-images.githubusercontent.com/64614859/139506285-f71959dd-64cf-48d9-bdaa-96bcbf7ac1a8.png">

**Comment by parkr** [comment]
Give the binary a right click, and select "Open". Another prompt will show up, from which you can select "Open Anyway" or "Allow".

**Comment by dubadub** [comment]
@lenniecottrell thanks for reporting. I'll add notarisation to the release scripts as described here https://stackoverflow.com/a/64733472

**Comment by dubadub** [comment]
I fixed in the best possible way (as I know): signed binary and notarised it via Apple using my developer account.

It still can give a warning, but it's less scary: 
<img width="296" alt="Screenshot 2021-11-02 at 20 02 28" src="https://user-images.githubusercontent.com/4168619/139943882-bbe21aa3-377a-458e-a6ab-f188e5f63cac.png">.

If someone knows how to fix this message too, please share.
